# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AttendanceManagementApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'
  # Pods for AttendanceManagementApp

  target 'AttendanceManagementAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AttendanceManagementAppUITests' do
    # Pods for testing
  end

end
