env:
  global:
    - LC_CTYPE=en_US.UTF-8

matrix:
  include:
    - &podspec
      name: CocoaPods Lint
      os: osx
      language: objective-c
      osx_image: xcode10.3
      script:
        - pod lib lint --allow-warnings
    - &xcode
      name: Xcode 10.3 / Swift 5.0
      os: osx
      language: objective-c
      osx_image: xcode10.3
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release -sdk iphonesimulator -destination "name=iPhone 8" ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace APIKit.xcworkspace -scheme APIKit -configuration Release -sdk appletvsimulator -destination "name=Apple TV" ENABLE_TESTABILITY=YES | xcpretty -c
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - <<: *xcode
      name: Xcode 11.2 / Swift 5.1
      osx_image: xcode11.2
    - &swiftpm
      name: SwiftPM / Darwin / Swift 5.0
      os: osx
      language: generic
      osx_image: xcode10.3
      script:
        - swift build
        - swift test
    - <<: *swiftpm
      name: SwiftPM / Darwin / Swift 5.1
      osx_image: xcode11.2

notifications:
  email: false
